version: x.x.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
configuration: Release
build_script:
- cmd: build.cmd
test: off
artifacts:
- path: Release/net35
  name: de4dot-net35
- path: publish-netcoreapp2.1
  name: de4dot-netcoreapp2.1
- path: publish-netcoreapp3.0
  name: de4dot-netcoreapp3.0
