name: GitHub CI
on: push

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: |
          set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64;%PATH%
          build.cmd

      - uses: actions/upload-artifact@v1
        with:
          name: de4dot-net35
          path: Release/net35

      - uses: actions/upload-artifact@v1
        with:
          name: de4dot-netcoreapp2.1
          path: publish-netcoreapp2.1

      - uses: actions/upload-artifact@v1
        with:
          name: de4dot-netcoreapp3.0
          path: publish-netcoreapp3.0
